# -*- coding: utf-8 -*-
""""AI-Powered Governance Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a77RdT7oNl0wkgKXYEQD-5phUnymkrbi
"""

# ✅ No upload, no missing file, fully self-contained

import pandas as pd
import plotly.express as px

# --- Create a sample dataset (fake health data) ---
data = {
    'zone': ['Pune', 'Mumbai', 'Thane', 'Nagpur', 'Nashik'],
    'reported_cases': [120, 200, 150, 180, 130],
    'hospital_beds': [80, 150, 100, 120, 90],
    'complaints': [30, 50, 20, 60, 25],
    'response_days': [2, 3, 2, 5, 3]
}
df = pd.DataFrame(data)

# --- Show dataset ---
print("### Health Service Overview")
display(df.head())

# --- Plot chart ---
fig = px.bar(
    df,
    x='zone',
    y='response_days',
    title='Average Health Service Response Time by Zone',
    color='zone'
)
fig.show()

# --- AI-like summary ---
summary = (
    "✅ Public services show improvement in Pune and Thane.\n"
    "⚠️ Infrastructure and response delays persist in Nagpur.\n"
    "💡 Recommendation: Increase hospital capacity and staffing in Nagpur region."
)
print("\nAI Summary of Citizen Feedback:\n")
print(summary)